@startuml Tienda_ciclista

Class clientes{
   id_PK: INT 
   nombre: VARCHAR 
   telefono: BIGINT
   direccion: VARCHAR
   usuario: VARCHAR
   password: VARCHAR
   foto: VARCHAR
}

Class productos{
   cod_PK: INT 
   referencia: VARCHAR
   nombre: VARCHAR
   descripcion: VARCHAR
   cantidad: INT
   valorcomercial: DOUBLE
   foto: VARCHAR
   foto2: VARCHAR
   foto3: VARCHAR
   foto4: VARCHAR
   foto5: VARCHAR
   fecha: DATE 
   hora: TIME 
}

Class compras{
    cod_PK: INT
    fecha: DATE
    valor: DOUBLE
    fecha_de_entrega: DATE
    observacion: VARCHAR
    metodo_de_pago: VARCHAR
}

Class usuarios{
   id_PK:  INT 
   nombre: VARCHAR 
   telefono: BIGINT
   direccion: VARCHAR
   usuario: VARCHAR
   password: VARCHAR
   foto: VARCHAR
}


compras  *-- "Realizar" clientes
compras  *-- "Adquirir" productos

@enduml