@startuml Tienda_ciclista

Class clientes{
   id_PK: INT 
   nombre: VARCHAR 
   telefono: BIGINT
   direccion: VARCHAR
   usuario: VARCHAR
   password: VARCHAR
   foto: VARCHAR
}

Class productos{
   cod_PK: INT 
   referencia: VARCHAR
   nombre: VARCHAR
   descripcion: VARCHAR
   cantidad: INT
   valorcomercial: DOUBLE
   foto: VARCHAR
   foto2: VARCHAR
   foto3: VARCHAR
   foto4: VARCHAR
   foto5: VARCHAR
   fecha: DATE 
   hora: TIME 
}

Class info_ventas{
   cod_PK: INT
   cliente: INT
   fk_product: INT
   
}

Class usuarios{
   id_PK:  INT 
   nombre: VARCHAR 
   telefono: BIGINT
   direccion: VARCHAR
   usuario: VARCHAR
   password: VARCHAR
   foto: VARCHAR
}


info_ventas *-- "Realizar" clientes
info_ventas  *-- "Adquirir" productos

@enduml